// <auto-generated />
using System;
using GroceryListApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroceryListApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250317111823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroceryListApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "חלב וגבינות"
                        },
                        new
                        {
                            Id = 2,
                            Name = "טואלטיקה"
                        },
                        new
                        {
                            Id = 3,
                            Name = "בשר"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ירקות ופירות"
                        });
                });

            modelBuilder.Entity("GroceryListApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "קוטג'"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "חלב 3%"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "שמנת חמוצה"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "סבון"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "שמפו"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "נקניקיות"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "שוקיים"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "סלמון"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Name = "תפוח"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Name = "בננה"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "עגבניה"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "מלפפון"
                        });
                });

            modelBuilder.Entity("GroceryListApi.Models.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("GroceryListApi.Models.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("GroceryListApi.Models.Product", b =>
                {
                    b.HasOne("GroceryListApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GroceryListApi.Models.ShoppingListItem", b =>
                {
                    b.HasOne("GroceryListApi.Models.Product", "Product")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryListApi.Models.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("GroceryListApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GroceryListApi.Models.Product", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("GroceryListApi.Models.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
